.github/workflows/docs.yml

Will auto-update documentation on push to main or when manually triggered.

ci: Add docs.yml to automate documentation updates

---

docs/welcome/welcome.md

Moved from https://github.com/phylum-dev/cli/pull/846

docs: Update Welcome page and add to VCS

---

docs/home/welcome.md

Since `phylum init` provides a better user experience than manually
creating projects yourself, we should recommend it over the other
alternatives.

Switch to `phylum init` for project setup

---

docs/knowledge_base/policy_apply.md

Update image url to work on `readme.com`

docs: fix image url

---

docs/integrations/README.txt
docs/integrations/azure_pipelines.md
docs/integrations/bitbucket_pipelines.md
docs/integrations/git_precommit.md
docs/integrations/github_actions.md
docs/integrations/gitlab_ci.md
docs/integrations/integrations_overview.md

These are direct copies of the pages. The content was not changed (and did not need to be changed).
Closes #27

docs: copy 'Integrations' category pages from `phylum-ci` repo

---

docs/knowledge_base/api-keys.md
docs/knowledge_base/groups.md
docs/support/contact_us.md
docs/support/security.md

These are direct copies of the pages. The content was not changed (and did not need to be changed).
Closes #28

docs: copy 'Support' and 'KB' category pages from `cli` repo

---

docs/analytics/bad_author.md
docs/analytics/bus_factor.md
docs/analytics/compiled_binary.md
docs/analytics/dependency_confusion.md
docs/analytics/env_var_enumeration.md
docs/analytics/ephemeral_domain.md
docs/analytics/executes_code_at_remote_url.md
docs/analytics/expired_author_domains.md
docs/analytics/hostname_identification.md
docs/analytics/invokes_native_code.md
docs/analytics/ip_identification.md
docs/analytics/npm_hooks.md
docs/analytics/obfuscated_javascript.md
docs/analytics/obfuscated_python.md
docs/analytics/odd_dependency.md
docs/analytics/remote_exe_ref_or_run.md
docs/analytics/secrets.md
docs/analytics/strange_python_imports.md
docs/analytics/suspicious_setup_commands.md
docs/analytics/suspicious_url_references.md
docs/analytics/trivial_package.md
docs/analytics/typosquatting.md
docs/analytics/webhook_exfil.md

These are direct copies of the pages. The content was not changed (and did not need to be changed).
Closes #29

docs: copy 'Analytics' category pages from private repo

---

docs/knowledge_base/policy_development.md

update policy suppression

---

docs/knowledge_base/threat_feed.md

Adding a docs page for the threat feed

docs: Create threat_feed.md

---

docs/home/defend_your_workstation.md

Add "Defend Your Workstation" page to be used as a quick reference to get someone started with this feature.
Close #43

docs: Add "Defend Your Workstation" page

---

docs/integrations/integrations_overview.md
docs/integrations/netskope.md

Adds instructions for Netskope integration subscribers.
Closes #64

add netskope integration docs

---

docs/knowledge_base/threat_feed.md

add eco/name/ver endpoint docs

---

docs/knowledge_base/search.md
site/sidebars.js

- Add `search` page to sidebar
- Update CVSS example to be more clear about `.` usage

docs: update sidebar to include the new search page

---

docs/knowledge_base/issue_tags.md

- Update `issue_tags.md` with all currently available tags

docs: Update `issue_tags.md`

---

docs/knowledge_base/issue_tags.md

- Update malware bazaar rule with correct severity

docs: Update issue_tags.md

---

docs/knowledge_base/policy_examples.md

When I updated the policy documentation, I missed these package lines.

fix example policy packages

---

docs/analytics/license_commercial_risk.md
docs/analytics/license_source_code_distribution.md
docs/knowledge_base/issue_tags.md

Update the license rules
- Updates license rule to show issue when a license prohibits commercial usage
- Adds doc page
- Add new issue when license requires source code distribution.
Closes https://github.com/phylum-dev/documentation/issues/182

Update license rules

---

docs/knowledge_base/threat_feed.md

Update docs for cursor based pagination

---

docs/artifact_repositories/about.md
docs/artifact_repositories/maven.md
site/sidebars.js

Draft until we can get prod issues with Maven sorted.

Add Maven repository proxy documentation

---

docs/package_firewall/cargo.md
docs/package_firewall/golang.md
docs/package_firewall/maven.md
docs/package_firewall/npm.md
docs/package_firewall/nuget.md
docs/package_firewall/pypi.md

This patch adds the improved error responses recently introduced to Aviary to the documentation for the individual package managers.

Add improved firewall errors

---

docs/home/changelog.md

Add updates to CHANGELOG for SOC2 compliance requirements.

Add recent updates to CHANGELOG

---

docs/package_firewall/about.md
docs/package_firewall/unsupported.md
site/sidebars.js

ref https://veracode.atlassian.net/browse/SFP-165

Add documentation about unsupported firewall use cases.
