phylum-dev/documentation

docs/knowledge_base/faq.md

This change adds a Frequently Asked Questions (FAQ) page and populates it with some initial content. The page has been added under the "Knowledge Base" category and the first question comes from the current "Processing" page hosted at https://docs.phylum.io/docs/processing
That processing page is not currently tracked in source control. It only lives on the readme.com site. The other page like that is the "Phylum Package Score" at https://docs.phylum.io/docs/phylum-package-score
That page will not be ported since the decision was to abandon it given the content will not be relevant going forward.
Closes #30

docs: add an FAQ page

---

docs/knowledge_base/api-keys.md

Fix a typo that @maxrake found during our meeting this morning.

Fix typo in API key doc

---

docs/knowledge_base/issue_tags.md

This KB article will be helpful for people writing custom policies that want to include specific issue types.

docs: Add table outlining Issue Tags

---

docs/analytics/env_var_enumeration.md
docs/analytics/remote_exe_ref_or_run.md
docs/integrations/github_app.md
docs/knowledge_base/create_project.md
docs/knowledge_base/issue_tags.md

This PR adds a "Phylum Project Creation" page. It was originally part of #54, but that PR was superseded by #56. The new page will exist in the Knowledge Base and can be referenced from there. It details the ways in which a Phylum project can be created. Some additional documentation cleanup was done in this change as well:
* Change instances of `PyPi` to `PyPI` for consistency and correctness
* Ensure FAW sections are formatted consistently throughout the repo
* Clean up the "Issue Tags" page
* Remove extra whitespace
* Add links to rules
* Be consistent on punctuation
* Clarify issue descriptions based on a review of the underlying rules

docs: add "Phylum Project Creation" page

---

docs/home/changelog.md
docs/home/defend_your_workstation.md
docs/integrations/github_app.md

With the recent release of the CLI v5.7.1, documentation was updated. The big changes are:
* https://docs.phylum.io/docs/analyzing-dependencies was replaced by https://docs.phylum.io/docs/analyzing_dependencies and https://docs.phylum.io/docs/supported_lockfiles
* https://docs.phylum.io/docs/lockfile-generation was replaced by https://docs.phylum.io/docs/lockfile_generation
This PR updates the links in this repository to match.

docs: update dead links

---

docs/integrations/azure_pipelines.md
docs/integrations/bitbucket_pipelines.md
docs/integrations/git_precommit.md
docs/integrations/gitlab_ci.md

phylum-dev/phylum-ci#364 introduced breaking changes. The `--lockfile`/`-l` argument was changed to `--depfile`/`-d`. This change updates the docs to match. The PR should not be merged until a `phylum-ci` release with the changes is out.

docs: account for breaking `phylum-ci` changes

---

site/docusaurus.config.js
site/static/CNAME

This PR is part of the larger coordinated effort to cutover the Phylum documentation site from being hosted on README.com to GitHub Pages.
It should not be merged until the following other tasks are complete or can happen at the same time:
* "Custom Domain" value in [GitHub repo settings](https://github.com/phylum-dev/documentation/settings/pages) changed
* https://github.com/phylum-dev/infrastructure/pull/1167
* PRs for updating URLs in other repos are merged

docs: update CNAME record to point to docs.phylum.io

---

.github/workflows/docs.yml
README.md
docs/analytics/expired_author_domains.md
docs/analytics/remote_exe_ref_or_run.md
docs/analytics/suspicious_setup_commands.md
docs/support/contact_us.md
site/docusaurus.config.js

This PR addresses the issue of the "Last updated on" time and author being the same for every page and set to the most recent commit time/author. It modifies the git fetch depth in the `docs` workflow used for publishing the site, as detailed in this discussion: https://github.com/facebook/docusaurus/issues/2798#issuecomment-636602951.
This PR also takes the opportunity to update the Discord Phylum Community link so that it shows "Louis (lwlang)" as the inviter instead of "Bill@Phylum (bill_phylum)".
Finally, a few grammar updates were made and a few typos fixed.

fix: show correct last update time/author

---

CONTRIBUTING.md
site/docusaurus.config.js
site/package-lock.json
site/package.json
site/sidebars.js

This change adds the official Docusaurus `plugin-client-redirects` plugin, as discussed in the https://github.com/phylum-dev/rules/pull/445 PR comments. Doing so ensures the existing links that haven't been (or can't be) changed will continue to work. These links could exist anywhere, but the known locations include:
* The main phylum.io website
* The blog.phylum.io website
* The "Learn more" links in issue card text
* `rules`, UI, database, etc.

feat: add client side redirects

---

CONTRIBUTING.md
site/docusaurus.config.js
site/package-lock.json
site/package.json

This change bumps the version of docusaurus from v3.0.1 to [v3.1.0](https://github.com/facebook/docusaurus/releases/tag/v3.1.0) and accounts for the new features found in the release. Namely, the new `onBrokenAnchors` configuration is added and set to `throw` to match the existing related settings. Additionally, a typo in `CONTRIBUTING.md` was fixed.

Bump docusaurus to v3.1.0

---

.github/workflows/update_submodule.yml
ext/README.md

The change in #97 was not the solution as a manual trigger to the updated workflow resulted in the same error. Further investigation revealed that the submodule was not updated (did not have the latest commits and tags) before the workflow attempted to checkout the newly created tag.
This change accounts for that update step. It also ensures that each submodule command in the workflow and in documentation is acting on the explicitly named submodule so that other submodules (which don't exist yet but may soon) are not accidentally changed/updated.
Finally, the `actions/checkout` option to `fetch-tags` was removed since it was determined to act on the `documentation` repo itself and not any of the submodules. The `documentation` repo does not have any tags and, even if it did, they aren't …

ci: update submodules in submodule update workflow

---

site/package-lock.json
site/package.json

This change bumps the version of docusaurus from v3.1.1 to [v3.2.0](https://github.com/facebook/docusaurus/releases/tag/v3.2.0). There are no new features or bug fixes that need to be accounted for.

Bump docusaurus to v3.2.0

---

site/package-lock.json
site/package.json

This change bumps the version of Docusaurus from v3.2.0 to [v3.3.2](https://docusaurus.io/blog/releases/3.3). There are no new features or bug fixes that need to be accounted for. A local Phylum analysis was performed and came back clean.

Bump docusaurus to v3.3.2

---

site/package-lock.json
site/package.json

This change bumps the version of docusaurus from v3.3.2 to [v3.4.0](https://github.com/facebook/docusaurus/releases/tag/v3.4.0). There are no new features or bug fixes that need to be accounted for. The changes were tested locally by successfully building and serving the site.

Bump `docusaurus` to v3.4.0

---

docs/knowledge_base/policy_basics.md
docs/knowledge_base/policy_development.md
docs/knowledge_base/policy_examples.md

This PR updates the policy documentation to reflect the new `policy.v1` format. The previous format still works, but the new format is preferred.
There's currently an issue with the policy SDK zip where the root element is missing. I'm pretty sure it was unintentional and there isn't a trick to making the opa CLI load data with a prefix. It should be like this one:
[constants.json](https://github.com/user-attachments/files/15537760/constants.json)

update policy documentation for v1

---

docs/integrations/integrations_overview.md
site/docusaurus.config.js
site/sidebars.js

The site banner section was intentionally commented out and left in so the format would not need to be looked up for future updates.

docs: expose Jenkins integration doc and disable banner

---

site/docusaurus.config.js

This is what the docs look like currently:
---
This is what the docs look like with the change in this PR:

docs: enable 'groovy' code formatting

---

docs/knowledge_base/threat_feed.md

Customer should be encouraged to use the primary API for package lookups.

docs: Remove Threat Feed - Package Lookup Endpoint section

---

docs/package_firewall/npm.md

For NPM packages, the dependency firewall proxies the available package metadata but not the package content. In the returned metadata, the tarball location is pointing at the regular registry.npmjs.org location. If you don't set `replace-registry-host`, the [default value of `'registry.npmjs.org'`](https://github.com/npm/cli/blob/7788ef20aff336c95836e64997a7264913924c4b/workspaces/arborist/lib/arborist/index.js#L83-L85) will cause the NPM CLI to ["fix" the URL](https://github.com/npm/cli/blob/4e81a6a4106e4e125b0eefda042b75cfae0a5f23/workspaces/arborist/lib/arborist/reify.js#L844-L848) that we intentionally didn't change, resulting in 404 errors when trying to download the package.

add replace-registry-host=never

---

site/docusaurus.config.js

This change is a result of a broken link during a live demo and due to a change on 25 OCT 2023 in the `rules` repo where the `trivial_package` rule was renamed to `minimal_code`.
This change has been built and tested locally.

Add redirect for trivial_package

---

site/package-lock.json
site/package.json

This change bumps the version of `docusaurus` from v3.4.0 to v3.5.2. There are no new features or bug fixes that need to be accounted for. The changes were tested locally by successfully building and serving the site. Changelogs for the versions included in this upgrade:
* [v3.5.0](https://github.com/facebook/docusaurus/releases/tag/v3.5.0)
* [v3.5.1](https://github.com/facebook/docusaurus/releases/tag/v3.5.1)
* [v3.5.2](https://github.com/facebook/docusaurus/releases/tag/v3.5.2)

Bump `docusaurus` to v3.5.2

---

docs/artifact_repositories/api.md

This documents the `GET /webhooks` endpoint of Aviary and also adds missing warnings about persisting the token into the shell history where relevant.

Add documentation for retrieving Aviary webhooks

---

docs/artifact_repositories/cargo.md
docs/artifact_repositories/maven.md
docs/artifact_repositories/npm.md
docs/artifact_repositories/pypi.md
docs/artifact_repositories/rubygems.md

---
NPM and PyPI do **not** seem to actually work yet. It seems like we need to explicitly support `%2F` as a separator in Aviary.

Add Aviary org docs

---

docs/artifact_repositories/about.md
docs/artifact_repositories/nuget.md
site/sidebars.js

Documentation for https://github.com/phylum-dev/aviary/pull/108.

Add NuGet Artifact Repository documentation

---

docs/knowledge_base/continuous_monitoring.md

The current job concept is explained directly on the continuous monitoring page since this is where the impact is most clearly seen.
This PR should be the final change needed for the [default label story](https://github.com/phylum-dev/roadmap/issues/271#issuecomment-2419674094)

Explain the effect of current job on monitoring

---

site/babel.config.js
site/docusaurus.config.js
site/package-lock.json
site/package.json

This change bumps the version of `docusaurus` from v3.5.2 to v3.6.3.
The new "Docusaurus Faster" feature added in v3.6.0 was applied with a feature flag in the config. It makes use of SWC js loader, which allows for removing the Babel config file at `site/babel.config.js`. It also uses `rspack` instead of `webpack`, which required a few small changes to the config (mostly naming and comment reminders). Overall, using the new features allows the site to build in one third the time as before, at least when measured from local builds.
The changes were tested locally by successfully building and serving the site. Changelogs for the versions included in this upgrade:
* [v3.6.0](https://github.com/facebook/docusaurus/releases/tag/v3.6.0)
* …

Bump `docusaurus` to v3.6.3

---

docs/artifact_repositories/about.md
docs/artifact_repositories/golang.md
site/sidebars.js

---
While I have tested this by locally denying packages, I was not able to get policies working with the Golang ecosystem. While that shouldn't change anything about this documentation, I can not positively confirm the ecosystem actually works in staging.
Closes #250

Add Golang artifact repository documentation

---

docs/package_firewall/golang.md

This fixes an issue with golang's firewall error examples which erroneously included part of the Cargo output.
To reduce confusion the `github.com` host has also been changed to `example.org`, since github requires a user/organization in its path in addition to the repository itself.

Fix malformed golang error examples

---

.github/workflows/auto_updates.yml
site/package-lock.json
site/package.json

This change bumps the version of `docusaurus` from v3.6.3 to v3.7.0. There are no new features or bug fixes that need to be accounted for. The changes were tested locally by successfully building and serving the site. Changelogs for the versions included in this upgrade:
* [v3.7.0](https://github.com/facebook/docusaurus/releases/tag/v3.7.0)
The version of `react` was updated at this time to v19.x since this release of `docusaurus` suggests it, prior to the next release when it will be mandatory.
Additionally, this change updates the weekly dependency update workflow, to bring it up to date with the rest of the org and also allow for an earlier update time so that it will be more likely that all packages are processed by the time someone reviews the changes.

Bump `docusaurus` to v3.7.0

---

docs/package_firewall/pypi.md

This change updates the command to use to add the `phylum` source repo so that it makes use of the `--priority primary` option, which will be required in a future release of Poetry and makes it more explicit now. The output when **all** versions of a package are blocked is also updated to match the current output text when this happens.

Update Poetry package firewall command and output

---

site/docusaurus.config.js
site/package-lock.json
site/package.json

This change bumps the version of `docusaurus` from v3.7.0 to v3.8.1. There are no new features or bug fixes that need to be accounted for. The changes were tested locally by successfully building and serving the site. Changelogs for the versions included in this upgrade:
* [v3.8.0](https://github.com/facebook/docusaurus/releases/tag/v3.8.0)
* [v3.8.1](https://github.com/facebook/docusaurus/releases/tag/v3.8.1)
The next major version of Docusaurus (v4) is coming and there are [Future Flags](https://docusaurus.io/blog/releases/3.8#future-flags) that can be opted into to prepare for that release. All of those flags were accepted.

Bump `docusaurus` to v3.8.1

---

docs/home/welcome.md
docs/support/contact_us.md

This change was initiated due to a potential customer reading the documentation and following the link to register for the free version. When it didn't work for them, they used the contact info published on the site to ask about the issue. I informed them of the new model of operations and told them we would update the documentation to match. This is that update.

Remove references to the free Community version

---

site/docusaurus.config.js
site/package-lock.json
site/package.json

This change bumps the version of `docusaurus` from v3.8.1 to v3.9.1. There are no new features or bug fixes that need to be accounted for. The changes were tested locally by successfully building and serving the site. Changelogs for the versions included in this upgrade:
* [v3.9.0](https://github.com/facebook/docusaurus/releases/tag/v3.9.0)
* [v3.9.1](https://github.com/facebook/docusaurus/releases/tag/v3.9.1)
The next major version of Docusaurus (v4) is coming and the config setting `siteConfig.onBrokenMarkdownLinks` will be removed in favor of `siteConfig.markdown.hooks.onBrokenMarkdownLinks`. The change was made now since it was deprecated in this upgrade. Additionally, a new setting for `siteConfig.markdown.hooks.onBrokenMarkdownImages` was introduced and adopted here.

Bump `docusaurus` to v3.9.1
